<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Template.Domain\Template.Domain.csproj" />
    <ProjectReference Include="..\shared\Template.Contracts\Template.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Mapster.DependencyInjection" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.FluentValidation" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

</Project>
