<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Conductor.Domain\Conductor.Domain.csproj" />
    <ProjectReference Include="..\shared\Conductor.Contracts\Conductor.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" />
    <PackageReference Include="Mapster.DependencyInjection" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

</Project>
