// <auto-generated />
using System;
using Conductor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conductor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConductorDbContext))]
    [Migration("20260613210333_UpdateAtCreatedAt")]
    partial class UpdateAtCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Conductor.Domain.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Conductor.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Conductor.Domain.JobExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExecutedByAgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedByAgentId");

                    b.HasIndex("JobId");

                    b.ToTable("JobExecutions");
                });

            modelBuilder.Entity("Conductor.Domain.Job", b =>
                {
                    b.OwnsOne("Conductor.Domain.ValueObjects.Command", "Command", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Arguments")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Arguments");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeoutSeconds");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Command");

                            b1.Property<string>("WorkingDirectory")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("WorkingDirectory");

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsOne("Conductor.Domain.ValueObjects.CronExpression", "CronExpression", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("CronExpression");

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Command")
                        .IsRequired();

                    b.Navigation("CronExpression")
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Domain.JobExecution", b =>
                {
                    b.HasOne("Conductor.Domain.Agent", "ExecutedByAgent")
                        .WithMany()
                        .HasForeignKey("ExecutedByAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Domain.Job", "Job")
                        .WithMany("Executions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Conductor.Domain.ValueObjects.ExecutionResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("JobExecutionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ErrorMessage")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("ErrorMessage");

                            b1.Property<string>("StdErr")
                                .HasColumnType("TEXT")
                                .HasColumnName("StdErr");

                            b1.Property<string>("StdOut")
                                .HasColumnType("TEXT")
                                .HasColumnName("StdOut");

                            b1.HasKey("JobExecutionId");

                            b1.ToTable("ExecutionResults", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobExecutionId");

                            b1.OwnsOne("Conductor.Domain.ValueObjects.ExitCode", "ExitCode", b2 =>
                                {
                                    b2.Property<Guid>("ExecutionResultJobExecutionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Value")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("ExitCode");

                                    b2.HasKey("ExecutionResultJobExecutionId");

                                    b2.ToTable("ExecutionResults");

                                    b2.WithOwner()
                                        .HasForeignKey("ExecutionResultJobExecutionId");
                                });

                            b1.Navigation("ExitCode")
                                .IsRequired();
                        });

                    b.Navigation("ExecutedByAgent");

                    b.Navigation("Job");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Conductor.Domain.Job", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
